### ISSUE TITLE
Issue on docs - does not work

### ISSUE THREAD

**Issue by vishnuav** [Benzinga/doc-site-mintlify#6]
Path: /benzinga-apis/newsfeed-stream-v1/get-stream

I get the error "An error occurred while making the request: requests must have an https protocol"

curl --request GET \
  --url wss://api.benzinga.com/api/v1/news/stream \
  --header 'Key: 0a73c73c3b0843949e7944b53478daee'

**Comment by tommycotter** [comment]
Hi, 

/benzinga-apis/newsfeed-stream-v1/get-stream is provisioned via API keys. 

Please reach out to licensing@benzinga.com for access!

Thanks.
