### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by kevinjpb14** [Benzinga/doc-site-mintlify#7]
Path: /benzinga-apis/bars/get-bars  is out service

**Comment by kevinjpb14** [comment]
https://api.benzinga.com/api/v2/bars

**Comment by tommycotter** [comment]
Hi Kevin, 

/benzinga-apis/bars/get-bars access is provisioned via API keys. 

Please reach out to licensing@benzinga.com for access!

Thanks.
